/**
 * Expresscart
 * Expresscart API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Product { 
    id?: any | null;
    title?: any | null;
    description?: any | null;
    price?: any | null;
    imgUrl?: any | null;
    createdAt?: any | null;
    updatedAt?: any | null;
    UserId?: any | null;
    User?: any | null;
}

